version: '3.9'

services:
  server_python:
    build: ./docker/python
    command: python ./src/main/main.py
    volumes:
      - ./server/python:/usr/local/grpc/src
      - ./protos:/usr/local/grpc/protos
    tty: true

  client_python:
    build: ./docker/python
    volumes:
      - ./client/python:/usr/local/grpc/src
      - ./protos:/usr/local/grpc/protos
    environment:
      GRPC_SERVER_HOST: server_python
      GRPC_SERVER_PORT: 3000
    tty: true
